# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Movies' do

	pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'SwiftyJSON'
    pod 'RxAlamofire'
    pod 'RealmSwift'

end
